# ConL-IME settings
# encoding: utf-8

config_version: "0.22"

app_options:
  cmd.exe:
    ascii_mode: true
  conhost.exe:
    ascii_mode: true

style:
  color_scheme: default
  font_face: Microsoft YaHei
  font_point: 14
  horizontal: true
  fullscreen: false
  inline_preedit: false
  preedit_type: composition
  display_tray_icon: false
  label_format: "%s."
  layout:
    min_width: 160
    min_height: 0
    border_width: 3
    margin_x: 12
    margin_y: 12
    spacing: 10
    candidate_spacing: 5
    hilite_spacing: 4
    hilite_padding: 2
    round_corner: 4

preset_color_schemes:
  default:
    name: "Default"
    author: "skoj <skoj@qq.com>"
    text_color: 0x666666
    candidate_text_color: 0x000000
    back_color: 0xFFFFFF
    border_color: 0xE2E2E2
    hilited_text_color: 0x000000
    hilited_back_color: 0xFFFFFF
    hilited_candidate_text_color: 0xFFFFFF
    hilited_candidate_back_color: 0xCE7539
  dark:
    name: "Dark"
    author: "雨過之後、佛振"
    text_color: 0xc2c2c2
    back_color: 0x444444
    border_color: 0x444444
    candidate_text_color: 0xeeeeee
    hilited_text_color: 0xeeeeee
    hilited_back_color: 0x444444
    hilited_candidate_label_color: 0xfafafa
    hilited_candidate_text_color: 0xfafafa
    hilited_candidate_back_color: 0xd8bf00
    comment_text_color: 0x808080
    hilited_comment_text_color: 0x444444

